# Generated by Django 3.0 on 2019-12-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_twit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Понравилось'),
        ),
    ]
